#!/bin/sh /etc/rc.common

# https://openwrt.org/docs/guide-developer/procd-init-script-example
START=99
STOP=01
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /bin/sh "/root/startlogging"
	procd_close_instance
}

stop_service() {
	procd_open_instance
	procd_set_param command /bin/sh "/root/stoplogging"
	procd_close_instance
}
